apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- resources.yaml

images:
- name: goserver
  newName: bcdscrypto/gitopsfc
  newTag: 4edd3a6951975234ce34ccf2b98459fdcf6821ef
