apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- resources.yaml

images:
- name: goserver
  newName: bcdscrypto/gitopsfc
  newTag: b5ab780b3d03e64bfa43b3978e23d91dc1b1ab00
